### ISSUE TITLE
Missing .gitmodules file

### ISSUE THREAD

**Issue by apmorton** [DlangScience/cblas#29]
Commit 48d707dc0300b5582756b7149d89c211e2f28ea3 added a submodule `subprojects/mir-core` but did not commit a corresponding `.gitmodules` file.

This prevents anyone from recursively cloning this repository as git does not know where to clone `subprojects/mir-core` from.

**Comment by 9il** [comment]
Ah, that is the bug. Thank you

**Comment by 9il** [comment]
fixed in v2.3.1
